name: cicd

on:
  push:
      branches: [master]

jobs:

  deploy-app:
    runs-on: ubuntu-latest
    steps:
    - name: actions/checkout@v4
      uses: actions/checkout@v4
    - name: start-app
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_PRIV_KEY }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        script_stop: true
        script: |
              cd ~/agentic-rag-demo
              systemctl --user stop agentic-rag.service
    - name: copy-files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_PRIV_KEY }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        source: "./*"
        target: /home/${{ secrets.SSH_USERNAME }}/agentic-rag-demo
    - name: deploy-app
      uses: appleboy/ssh-action@v1.0.3
      env:
        DUMMY_VAR: 1
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_PRIV_KEY }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        script_stop: true
        envs: DUMMY_VAR
        script: |
              cd ~/agentic-rag-demo
              python3 -m pip install --break-system-packages -r requirements.txt
              cp .env.example .env
              > .env
              # putting dummy env var in .env file just to show how to export env vars from secrets in this pipeline
              echo "DUMMY_ENV_VAR=${DUMMY_VAR}" >> .env
              mv .streamlit/config.remote.toml .streamlit/config.toml
              systemctl --user start agentic-rag.service
